name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-setuptools \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            openjdk-17-jdk \
            autoconf \
            libtool \
            unzip \
            zip \
            libltdl7-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            zlib1g:i386

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: bin/*.apk
